apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cart-app
  namespace: argocd
spec:
  project: cart
  source:
    repoURL: git@github.com:Naphatsara/nonprod-k8s-manifests.git
    targetRevision: main
    path: dev/pedjeab/cart 
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
