apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cart
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io  
spec:
  description: Team A
  destinations:
  - name: '*'
    namespace: '*'
    server: '*'  
  clusterResourceWhitelist:
  - group: ""
    kind: Namespace
  roles:
  - description: Read Only
    name: read-only
    policies:
    - p, proj:cart:read-only, applications, get, cart/*, allow
  - description: Read Write
    name: read-write   
    policies:
    - p, proj:cart:read-write, applications, get, team-a/*, allow
    - p, proj:cart:read-write, applications, sync, team-a/*, allow
    - p, proj:cart:read-write, applications, update, team-a/*, allow        
  sourceRepos:
  - git@github.com:Naphatsara/nonprod-k8s-manifests.git
  
