apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: idp-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:Naphatsara/idp-app.git
    targetRevision: main
    path: platform
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
